# Generated by Django 5.0.1 on 2024-02-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
