# Generated by Django 5.0.1 on 2024-02-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(default='Default Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='default_image.jpg', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(default='default_img.jpg', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Default Title', max_length=50),
        ),
    ]
