# Generated by Django 5.0.1 on 2024-02-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_alter_product_category_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='amazon/images'),
        ),
    ]
