# Generated by Django 5.0.1 on 2024-02-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=150),
        ),
    ]
