# Generated by Django 5.0.1 on 2024-02-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_alter_product_category_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Default Category', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://cdn.dummyjson.com/product-images/24/thumbnail.jpg', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='amazon/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
