# Generated by Django 5.0.1 on 2024-02-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0018_alter_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
    ]
