# Generated by Django 5.0.1 on 2024-02-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0021_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
